config <- read_json("config_file.json")
an_meta <- file.path(config$project_dir, config$analysis_metadata) %>% fread() %>% as_tibble()
an_type_meta <- file.path(config$project_dir, config$analysis_type_metadata) %>% fread() %>% as_tibble()
lib_meta <- file.path(config$project_dir, config$library_metadata) %>% fread() %>% as_tibble()
comb_lib_meta <- file.path(config$project_dir, config$combined_library_metadata) %>% fread() %>% as_tibble()
bb_meta <- file.path(config$project_dir, config$building_block_metadata) %>% fread() %>% as_tibble()
run_meta <- file.path(config$project_dir, config$sequencing_run_metadata) %>% fread() %>% as_tibble()
ct_file_meta <- file.path(config$project_dir, config$count_filename_metadata) %>% fread() %>% as_tibble()
samp_meta <- file.path(config$project_dir, config$sample_metadata) %>% fread() %>% as_tibble()
targ_meta <- file.path(config$project_dir, config$target_metadata) %>% fread() %>% as_tibble()
resin_meta <- file.path(config$project_dir, config$resin_metadata) %>% fread() %>% as_tibble()
scr_meta <- file.path(config$project_dir, config$screen_metadata) %>% fread() %>% as_tibble()
agg_meta <- file.path(config$project_dir, config$aggregation_metadata) %>% fread() %>% as_tibble()