mkdir -p /chembio/datasets/proj/del/prototype/code/fun
mkdir -p /chembio/datasets/proj/del/prototype/code/pipe
mkdir -p /chembio/datasets/proj/del/prototype/code/script
mkdir -p /chembio/datasets/proj/del/prototype/data/smp001/count
mkdir -p /chembio/datasets/proj/del/prototype/data/smp001/raw
mkdir -p /chembio/datasets/proj/del/prototype/doc/ms
mkdir -p /chembio/datasets/proj/del/prototype/doc/slide
mkdir -p /chembio/datasets/proj/del/prototype/meta/chem/bb_avail
mkdir -p /chembio/datasets/proj/del/prototype/meta/chem/bb_valid
mkdir -p /chembio/datasets/proj/del/prototype/meta/chem/react
mkdir -p /chembio/datasets/proj/del/prototype/meta/lib/lib001
mkdir -p /chembio/datasets/proj/del/prototype/meta/expt/expt001/protocol
mkdir -p /chembio/datasets/proj/del/prototype/meta/expt/expt001/result
mkdir -p /chembio/datasets/proj/del/prototype/meta/smp
mkdir -p /chembio/datasets/proj/del/prototype/meta/seq
mkdir -p /chembio/datasets/proj/del/prototype/meta/an
mkdir -p /chembio/datasets/proj/del/prototype/result/an001/table
mkdir -p /chembio/datasets/proj/del/prototype/result/an001/plot